
package aplikasi_siswabaru;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *AHMAD GUNADI 2010010102
 * 
 */
public class Akun extends javax.swing.JFrame {

    /**
     * Creates new form Akun
     */
    public Akun() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nama = new javax.swing.JTextField();
        cmb_role = new javax.swing.JComboBox<>();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_akun = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nama.setBorder(null);
        getContentPane().add(txt_nama);
        txt_nama.setBounds(50, 94, 276, 20);

        cmb_role.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Admin", "Petugas" }));
        getContentPane().add(cmb_role);
        cmb_role.setBounds(380, 170, 290, 30);

        txt_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_user.setBorder(null);
        getContentPane().add(txt_user);
        txt_user.setBounds(50, 144, 276, 20);

        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_pass.setBorder(null);
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pass);
        txt_pass.setBounds(50, 190, 276, 20);

        tbl_akun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_akun.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_akun.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tbl_akun.setShowHorizontalLines(false);
        tbl_akun.setShowVerticalLines(false);
        tbl_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_akunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_akun);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 250, 890, 170);

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 120, 80, 23);

        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cari.setBorder(null);
        getContentPane().add(txt_cari);
        txt_cari.setBounds(390, 94, 270, 20);

        btn_refresh.setBackground(new java.awt.Color(255, 153, 0));
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh);
        btn_refresh.setBounds(741, 210, 100, 23);

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 210, 76, 23);

        lbl_id.setText("ID");
        getContentPane().add(lbl_id);
        lbl_id.setBounds(514, 259, 11, 14);

        btn_simpan.setBackground(new java.awt.Color(255, 153, 0));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(470, 210, 79, 23);

        btn_ubah.setBackground(new java.awt.Color(255, 153, 0));
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("Perbarui");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah);
        btn_ubah.setBounds(560, 210, 79, 23);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 50, 74, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kelola akun bg.jpg"))); // NOI18N
        jLabel7.setText("\n");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 890, 420);

        setSize(new java.awt.Dimension(904, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void refresh(){
        txt_nama.setText("");
        txt_user.setText("");
        txt_pass.setText("");
        cmb_role.setSelectedIndex(0);
        lbl_id.setText("");
        tampil();
    }
    private void tampil(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tbl.addColumn("Username");
        tbl.addColumn("Password");
        tbl.addColumn("Role");
        tbl_akun.setModel(tbl);
        try {
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM akun");
            int no = 0;
            while (res.next()) {
                tbl.addRow(new Object[]{
                    
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("username"),
                    res.getString("password"),
                    res.getString("role"),
                          
                });
                tbl_akun.setModel(tbl);
                no++;   
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,"Gagal Menampilkan Data");
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refresh();
        dispose();
        new Menu2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM akun WHERE nama LIKE '%" + txt_cari.getText() + "%'" + "");
            //ResultSet res = statement.executeQuery("SELECT * FROM tb_siswa");

            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID");
            tbl.addColumn("Nama");
            tbl.addColumn("Username");
            tbl.addColumn("Password");
            tbl.addColumn("Role");
            tbl_akun.setModel(tbl);

            int no = 0;
            while (res.next()) {
                tbl.addRow(new Object[]{
                    
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("username"),
                    res.getString("password"),
                    res.getString("role"),
                });
                tbl_akun.setModel(tbl);
                no++;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Gagal Menampilkan Data");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String id = lbl_id.getText();
        try {
            Statement statement;
            statement = (Statement) koneksi.getConnection().createStatement();
            statement.executeUpdate("DELETE FROM akun WHERE id='"+id+"'");
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");

            refresh();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Data Gagal Dihapus"+e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbl_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_akunMouseClicked
        // TODO add your handling code here:
        int i = tbl_akun.getSelectedRow();
        if (i==-1){
            return;
        }

        
         String id = (String) tbl_akun.getValueAt(i,0);
        lbl_id.setText(id);
        
        String nama = (String) tbl_akun.getValueAt(i,1);
        txt_nama.setText(nama);

        String user = (String) tbl_akun.getValueAt(i,2);
        txt_user.setText(user);
         String pass = (String) tbl_akun.getValueAt(i,3);
        txt_pass.setText(pass);
        
        String role =(String) tbl_akun.getValueAt(i,4);
        if (role.equals("Admin")) {
            cmb_role.setSelectedIndex(1);
        } else if (role.equals("Petugas")) {
            cmb_role.setSelectedIndex(2);
        }

 

        
    }//GEN-LAST:event_tbl_akunMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama, username, password, role, INSERT;

        nama = txt_nama.getText();
        username = txt_user.getText();
        password = txt_pass.getText();
        role = (String) cmb_role.getSelectedItem();
        
        try {
            Statement statement;
            statement = (Statement) koneksi.getConnection().createStatement();
            INSERT = "INSERT INTO akun VALUES (null,'"+nama+"','"+username+"','"+password+"','"+role+"')";
            statement.executeUpdate(INSERT);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            refresh();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan"+e.getMessage());
        }

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
         String nama, username, password, role;
         String id = lbl_id.getText(); 
         
        nama = txt_nama.getText();
        username = txt_user.getText();
        password = txt_pass.getText();
        role = (String) cmb_role.getSelectedItem();
        try {
            Statement statement;
            statement = (Statement) koneksi.getConnection().createStatement();
            statement.executeUpdate("UPDATE akun SET nama='"+nama+"', username='"+username+"', password='"+password+"', role='"+role+"'WHERE id='"+id+"'");
            JOptionPane.showMessageDialog(null,"Data  Berhasil Diperbarui");

            refresh();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Data  Gagal Diperbarui"+e.getMessage());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tbl_akun;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    private void masuk() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
